//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniYurt.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int OdemeID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public string OgrenciTC { get; set; }
        public Nullable<int> KalanTaksit { get; set; }
        public int odenenTutar { get; set; }
        public Nullable<System.DateTime> odemeTarihi { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
