//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniYurt.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Izınler = new HashSet<Izınler>();
            this.Odalar = new HashSet<Odalar>();
            this.Odemeler = new HashSet<Odemeler>();
        }
    
        public int OgrenciID { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string OgrenciTC { get; set; }
        public string OgrenciOkul { get; set; }
        public string OgrenciBolum { get; set; }
        public string OgrenciSınıf { get; set; }
        public Nullable<System.DateTime> OgrenciKayitTarihi { get; set; }
        public Nullable<int> KalacagiOda { get; set; }
        public string OgrenciTelefon { get; set; }
        public string VeliAdi { get; set; }
        public string VeliTelefon { get; set; }
        public string OgrenciAdresi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izınler> Izınler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odalar> Odalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odemeler> Odemeler { get; set; }
    }
}
